[project]
name = "optcg-metabot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "discord-py>=2.7.1",
    "matplotlib>=3.11.2",
    "pandas>=3.0.6",
    "pillow>=12.3.0",
    "python-dotenv>=1.2.3",
    "requests>=2.34.2",
    "schedule>=1.2.2",
]

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}
py-modules = ["utils"]

[tool.setuptools.packages.find]
where = ["src"]
include = ["bot*", "scrapers*"]
